import { Router, type IRouter } from "express";
import { requireCmsAuth } from "../middleware/auth";
import healthRouter from "./health";
import customersRouter from "./customers";
import servicesRouter from "./services";
import suppliersRouter from "./suppliers";
import contractsRouter from "./contracts";
import receiptsRouter from "./receipts";
import expensesRouter from "./expenses";
import accountsRouter from "./accounts";
import dashboardRouter from "./dashboard";
import reportsRouter from "./reports";
import auditLogsRouter from "./audit-logs";
import debtsRouter from "./debts";
import domainsRouter from "./domains";
import hostingsRouter from "./hostings";
import websitesRouter from "./websites";
import fanpagesRouter from "./fanpages";
import fanpageServicesRouter from "./fanpageServices";
import facebookAdsRouter from "./facebookAds";
import googleAdsRouter from "./googleAds";
import googleProfilesRouter from "./googleProfiles";
import employeesRouter from "./employees";
import billingPeriodsRouter from "./billing-periods";
import revenueRecognitionRouter from "./revenue-recognition";
import syncRouter from "./sync";
import invoicesRouter from "./invoices";
import taxRouter from "./tax";

const router: IRouter = Router();

router.use(healthRouter);
router.use(requireCmsAuth);
router.use(customersRouter);
router.use(servicesRouter);
router.use(suppliersRouter);
router.use(contractsRouter);
router.use(receiptsRouter);
router.use(expensesRouter);
router.use(accountsRouter);
router.use(dashboardRouter);
router.use(reportsRouter);
router.use(auditLogsRouter);
router.use(debtsRouter);
router.use(domainsRouter);
router.use(hostingsRouter);
router.use(websitesRouter);
router.use(fanpagesRouter);
router.use(fanpageServicesRouter);
router.use(facebookAdsRouter);
router.use(googleAdsRouter);
router.use(googleProfilesRouter);
router.use(employeesRouter);
router.use(billingPeriodsRouter);
router.use(revenueRecognitionRouter);
router.use(syncRouter);
router.use(invoicesRouter);
router.use(taxRouter);

export default router;
