/* eslint-disable */
// AUTO-GENERATED by scripts/seed-programmatic-landings.mjs
// Do not edit manually.

export type ProgrammaticGeneratedLanding = {
  slug: string;
  title: string;
  description: string;
  primaryKeyword: string;
  qualityScore: number;
};

export const WEBSITE_INDUSTRY_GENERATED: ProgrammaticGeneratedLanding[] = [
  {
    slug: "nha-khoa",
    title: "Thiết kế website nha khoa chuẩn SEO",
    description: "Landing theo ngành nha khoa tập trung chuyển đổi đặt lịch và SEO local.",
    primaryKeyword: "thiết kế website nha khoa",
    qualityScore: 88
  },
  {
    slug: "xay-dung",
    title: "Thiết kế website công ty xây dựng",
    description: "Landing theo ngành xây dựng tập trung hồ sơ năng lực và lead B2B.",
    primaryKeyword: "thiết kế website xây dựng",
    qualityScore: 70
  },
  {
    slug: "logistics",
    title: "Thiết kế website logistics và vận tải",
    description: "Landing pilot cho ngành logistics, cần bổ sung thêm bằng chứng dự án.",
    primaryKeyword: "thiết kế website logistics",
    qualityScore: 27
  },
];

export const LOCAL_SEO_GENERATED: ProgrammaticGeneratedLanding[] = [
  {
    slug: "ho-chi-minh",
    title: "SEO Website tại TP.HCM",
    description: "Landing local SEO tại TP.HCM cho doanh nghiệp SME.",
    primaryKeyword: "seo website tphcm",
    qualityScore: 79
  },
  {
    slug: "ha-noi",
    title: "SEO Website tại Hà Nội",
    description: "Landing local SEO tại Hà Nội theo cụm ngành và intent chuyển đổi.",
    primaryKeyword: "seo website ha noi",
    qualityScore: 74
  },
  {
    slug: "da-nang",
    title: "SEO Website tại Đà Nẵng",
    description: "Landing pilot local SEO Đà Nẵng.",
    primaryKeyword: "seo website da nang",
    qualityScore: 19
  },
];
